### ISSUE TITLE
404 on SublimeLinter-contrib-vale

### ISSUE THREAD

**Issue by craigmac** [SublimeLinter/package_control_channel#125]
I can't install the vale contrib plugin because I get a 404. Output:

```
Package Control: Error downloading package. HTTP error 404 downloading https://codeload.github.com/admhlt/SublimeLinter-contrib-vale/zip/v1.0.0.
error: Package Control
```

It seems 'admhlt' redirects to 'adamhollett' so that may be the problem, I'm not sure. I can't find anything related to this 'codeload' URL in any JSON file, any idea?

**Comment by kaste** [comment]
Usually redirect are fully transparent 🤔   I have updated the url.  Let's see if this helps.

**Comment by craigmac** [comment]
That worked with the URL change however it seems it hasn't been updated to newer API, I get these errors on install:

```
SublimeLinter: ERROR:
=====================

vale: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

vale: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

vale disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector
```

I believe it's trying to grab the tagged 1.0.0 version, whereas HEAD seems to have the fixes needed. Project looks unmaintained, someone forked it and the correct changes are there. If noones interested in submitting a PR I'll fork it and push a working version.

**Comment by kaste** [comment]
That's so unfortunate.  I looked at the code (at HEAD) and it looked like it could work.  But damn it it's not tagged.  

Must be a fork to leave the history intact.  Ideally @adamhollett would transfer the repo to you or someone else or to the SublimeLinter org so we have automatic redirects working.
