### ISSUE TITLE
Remove no longer existing SublimeLinter-contrib-groovyc repository

### ISSUE THREAD

**Issue by deathaxe** [SublimeLinter/package_control_channel#135]
SublimeLinter-contrib-groovyc does no longer exist and should be removed to prevent takeover attack.

Remove: https://github.com/SublimeLinter/package_control_channel/blob/ac0e4140a659b5aeb35be3e0ed8a0d2ab0636403/contrib.json#L610-L620

**Comment by kaste** [comment]
Yeah sure.
