### ISSUE TITLE
Fetch all repos by package name

### ISSUE THREAD

**Issue by FichteFoll** [SublimeLinter/package_control_channel#55]
~~Some linters in the `contrib.json` file do not have the `contrib` prefix.~~

Make ` 	fetch_all_repos.py` clone repos by the package name, not their repo name.

**Comment by braver** [comment]
I believe all do have the name set correctly, I checked recently and made some adjustments but may have missed one or two. A bunch don’t have contrib in the repo name, but it’s a bit hard to do something about that now. 

Also, but perhaps besides the point, I don’t care so much for the distinction. The intention was for the non-contrib ones to have passed a quality check, but a lot of the non-contrib plugins haven’t seen  maintenance in years and/or are just as insane as much of SL3.

**Comment by FichteFoll** [comment]
Ah right, I thought about that for a moment but then forgot. The ` 	fetch_all_repos.py` script clones by repo name, not by the package name. I guess that should be adjusted instead.
